// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders.proto

package orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	FulfilmentOrderId    string           `protobuf:"bytes,1,opt,name=fulfilment_order_id,json=fulfilmentOrderId,proto3" json:"fulfilment_order_id,omitempty"`
	CustomerOrderId      string           `protobuf:"bytes,2,opt,name=customer_order_id,json=customerOrderId,proto3" json:"customer_order_id,omitempty"`
	CreatedAt            string           `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Units                []*Unit          `protobuf:"bytes,4,rep,name=units,proto3" json:"units,omitempty"`
	ShipmentAddress      *ShipmentAddress `protobuf:"bytes,16,opt,name=shipment_address,json=shipmentAddress,proto3" json:"shipment_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetFulfilmentOrderId() string {
	if m != nil {
		return m.FulfilmentOrderId
	}
	return ""
}

func (m *Order) GetCustomerOrderId() string {
	if m != nil {
		return m.CustomerOrderId
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *Order) GetShipmentAddress() *ShipmentAddress {
	if m != nil {
		return m.ShipmentAddress
	}
	return nil
}

type ShipmentAddress struct {
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	FirstName            string   `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CompanyName          string   `protobuf:"bytes,8,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Street               string   `protobuf:"bytes,9,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber          string   `protobuf:"bytes,10,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	City                 string   `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,12,opt,name=country,proto3" json:"country,omitempty"`
	Phone                string   `protobuf:"bytes,13,opt,name=phone,proto3" json:"phone,omitempty"`
	ShippingDetails      string   `protobuf:"bytes,14,opt,name=shipping_details,json=shippingDetails,proto3" json:"shipping_details,omitempty"`
	Email                string   `protobuf:"bytes,15,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentAddress) Reset()         { *m = ShipmentAddress{} }
func (m *ShipmentAddress) String() string { return proto.CompactTextString(m) }
func (*ShipmentAddress) ProtoMessage()    {}
func (*ShipmentAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{1}
}

func (m *ShipmentAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentAddress.Unmarshal(m, b)
}
func (m *ShipmentAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentAddress.Marshal(b, m, deterministic)
}
func (m *ShipmentAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentAddress.Merge(m, src)
}
func (m *ShipmentAddress) XXX_Size() int {
	return xxx_messageInfo_ShipmentAddress.Size(m)
}
func (m *ShipmentAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentAddress proto.InternalMessageInfo

func (m *ShipmentAddress) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ShipmentAddress) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ShipmentAddress) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ShipmentAddress) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ShipmentAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *ShipmentAddress) GetHouseNumber() string {
	if m != nil {
		return m.HouseNumber
	}
	return ""
}

func (m *ShipmentAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ShipmentAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ShipmentAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ShipmentAddress) GetShippingDetails() string {
	if m != nil {
		return m.ShippingDetails
	}
	return ""
}

func (m *ShipmentAddress) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Unit struct {
	FreightCosts            float32       `protobuf:"fixed32,16,opt,name=freight_costs,json=freightCosts,proto3" json:"freight_costs,omitempty"`
	IsCancelled             bool          `protobuf:"varint,17,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	Sku                     string        `protobuf:"bytes,18,opt,name=sku,proto3" json:"sku,omitempty"`
	Price                   float32       `protobuf:"fixed32,19,opt,name=price,proto3" json:"price,omitempty"`
	DeliveryTimeExpires     string        `protobuf:"bytes,20,opt,name=delivery_time_expires,json=deliveryTimeExpires,proto3" json:"delivery_time_expires,omitempty"`
	ShipmentData            *ShipmentData `protobuf:"bytes,21,opt,name=shipment_data,json=shipmentData,proto3" json:"shipment_data,omitempty"`
	CustomerOrderUnitStatus string        `protobuf:"bytes,22,opt,name=customer_order_unit_status,json=customerOrderUnitStatus,proto3" json:"customer_order_unit_status,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{2}
}

func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (m *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(m, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

func (m *Unit) GetFreightCosts() float32 {
	if m != nil {
		return m.FreightCosts
	}
	return 0
}

func (m *Unit) GetIsCancelled() bool {
	if m != nil {
		return m.IsCancelled
	}
	return false
}

func (m *Unit) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Unit) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Unit) GetDeliveryTimeExpires() string {
	if m != nil {
		return m.DeliveryTimeExpires
	}
	return ""
}

func (m *Unit) GetShipmentData() *ShipmentData {
	if m != nil {
		return m.ShipmentData
	}
	return nil
}

func (m *Unit) GetCustomerOrderUnitStatus() string {
	if m != nil {
		return m.CustomerOrderUnitStatus
	}
	return ""
}

type ShipmentData struct {
	Carrier              string   `protobuf:"bytes,23,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrackingNumber       string   `protobuf:"bytes,24,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CreatedAt            string   `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentData) Reset()         { *m = ShipmentData{} }
func (m *ShipmentData) String() string { return proto.CompactTextString(m) }
func (*ShipmentData) ProtoMessage()    {}
func (*ShipmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{3}
}

func (m *ShipmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentData.Unmarshal(m, b)
}
func (m *ShipmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentData.Marshal(b, m, deterministic)
}
func (m *ShipmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentData.Merge(m, src)
}
func (m *ShipmentData) XXX_Size() int {
	return xxx_messageInfo_ShipmentData.Size(m)
}
func (m *ShipmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentData.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentData proto.InternalMessageInfo

func (m *ShipmentData) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *ShipmentData) GetTrackingNumber() string {
	if m != nil {
		return m.TrackingNumber
	}
	return ""
}

func (m *ShipmentData) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "orders.Order")
	proto.RegisterType((*ShipmentAddress)(nil), "orders.Shipment_address")
	proto.RegisterType((*Unit)(nil), "orders.Unit")
	proto.RegisterType((*ShipmentData)(nil), "orders.Shipment_data")
}

func init() { proto.RegisterFile("orders.proto", fileDescriptor_e0f5d4cf0fc9e41b) }

var fileDescriptor_e0f5d4cf0fc9e41b = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x95, 0xb4, 0x49, 0x93, 0xc9, 0xa6, 0x49, 0x9c, 0xa6, 0x35, 0x20, 0xa4, 0x10, 0x0e,
	0x04, 0x0e, 0x39, 0x84, 0x1b, 0x9c, 0xaa, 0x94, 0x03, 0x97, 0x22, 0x6d, 0xe1, 0xbc, 0x72, 0x77,
	0x27, 0x8d, 0xd5, 0xfd, 0x87, 0x3d, 0x8b, 0xc8, 0xf3, 0xf0, 0x30, 0x3c, 0x0c, 0x2f, 0x81, 0x3c,
	0xde, 0xa5, 0x4a, 0xb8, 0x79, 0xbe, 0xdf, 0x67, 0xef, 0x78, 0xbf, 0x31, 0x04, 0x85, 0x49, 0xd0,
	0xd8, 0x55, 0x69, 0x0a, 0x2a, 0x44, 0xd7, 0x57, 0x8b, 0x3f, 0x2d, 0xe8, 0x7c, 0x71, 0x4b, 0xb1,
	0x82, 0xe9, 0xb6, 0x4a, 0xb7, 0x3a, 0xcd, 0x30, 0xa7, 0x88, 0x71, 0xa4, 0x13, 0xd9, 0x9a, 0xb7,
	0x96, 0xfd, 0x70, 0xf2, 0x84, 0xd8, 0xfd, 0x39, 0x11, 0xef, 0x60, 0x12, 0x57, 0x96, 0x8a, 0x0c,
	0xcd, 0x93, 0xbb, 0xcd, 0xee, 0x51, 0x03, 0x1a, 0xef, 0x4b, 0x80, 0xd8, 0xa0, 0x22, 0x4c, 0x22,
	0x45, 0xf2, 0x84, 0x4d, 0xfd, 0x5a, 0xb9, 0x26, 0xb1, 0x80, 0x4e, 0x95, 0x6b, 0xb2, 0xf2, 0x74,
	0x7e, 0xb2, 0x1c, 0xac, 0x83, 0x55, 0xdd, 0xea, 0xb7, 0x5c, 0x53, 0xe8, 0x91, 0xd8, 0xc0, 0xd8,
	0xee, 0x74, 0xc9, 0xcd, 0xa9, 0x24, 0x31, 0x68, 0xad, 0x1c, 0xcf, 0x5b, 0xcb, 0xc1, 0x5a, 0x36,
	0xf6, 0xbb, 0x23, 0x1e, 0x8e, 0x9a, 0x1d, 0xd7, 0x5e, 0x58, 0xfc, 0x6e, 0xc3, 0xf8, 0xd8, 0x25,
	0x2e, 0xa0, 0x43, 0x9a, 0x52, 0x94, 0x1d, 0xee, 0xcb, 0x17, 0xae, 0xe5, 0xad, 0x36, 0x96, 0xa2,
	0x5c, 0x65, 0x28, 0xbb, 0xbe, 0x65, 0x56, 0x6e, 0x55, 0x86, 0xe2, 0x05, 0xf4, 0x53, 0xd5, 0xd0,
	0x33, 0xa6, 0x3d, 0x27, 0x30, 0x7c, 0x05, 0x41, 0x5c, 0x64, 0xa5, 0xca, 0xf7, 0x9e, 0xf7, 0x98,
	0x0f, 0x6a, 0x8d, 0x2d, 0x97, 0xd0, 0xb5, 0x64, 0x10, 0x49, 0xf6, 0x19, 0xd6, 0x95, 0xdb, 0xba,
	0x2b, 0x2a, 0x8b, 0x51, 0x5e, 0x65, 0xf7, 0x68, 0x24, 0xf8, 0xad, 0xac, 0xdd, 0xb2, 0x24, 0x04,
	0x9c, 0xc6, 0x9a, 0xf6, 0x72, 0xc0, 0x88, 0xd7, 0x42, 0xc2, 0x59, 0x5c, 0x54, 0x39, 0x99, 0xbd,
	0x0c, 0x58, 0x6e, 0x4a, 0x77, 0xbb, 0x72, 0x57, 0xe4, 0x28, 0x87, 0xfe, 0x76, 0x5c, 0x88, 0xb7,
	0xfe, 0x6f, 0x96, 0x3a, 0x7f, 0x88, 0x12, 0x24, 0xa5, 0x53, 0x2b, 0xcf, 0x7d, 0x76, 0x8d, 0x7e,
	0xe3, 0x65, 0x77, 0x00, 0x66, 0x4a, 0xa7, 0x72, 0xe4, 0x0f, 0xe0, 0x62, 0xf1, 0xab, 0x0d, 0xa7,
	0x2e, 0x1e, 0xf1, 0x1a, 0x86, 0x5b, 0x83, 0xfa, 0x61, 0x47, 0x51, 0x5c, 0x58, 0xf2, 0xa1, 0xb4,
	0xc3, 0xa0, 0x16, 0x37, 0x4e, 0x73, 0xb7, 0xd2, 0x36, 0x8a, 0x55, 0x1e, 0x63, 0x9a, 0x62, 0x22,
	0x27, 0xf3, 0xd6, 0xb2, 0x17, 0x0e, 0xb4, 0xdd, 0x34, 0x92, 0x18, 0xc3, 0x89, 0x7d, 0xac, 0xa4,
	0xe0, 0x8f, 0xb8, 0x25, 0x77, 0x6e, 0x74, 0x8c, 0x72, 0xca, 0x27, 0xfa, 0x42, 0xac, 0x61, 0x96,
	0x60, 0xaa, 0x7f, 0xa0, 0xd9, 0x47, 0xa4, 0x33, 0x8c, 0xf0, 0x67, 0xa9, 0x0d, 0x5a, 0x79, 0xc1,
	0x3b, 0xa7, 0x0d, 0xfc, 0xaa, 0x33, 0xfc, 0xe4, 0x91, 0xf8, 0x00, 0xc3, 0x7f, 0xb3, 0x93, 0x28,
	0x52, 0x72, 0xc6, 0x83, 0x33, 0xfb, 0x6f, 0x70, 0x1c, 0x0c, 0x83, 0xc6, 0x7b, 0xa3, 0x48, 0x89,
	0x8f, 0xf0, 0xfc, 0x68, 0xcc, 0xdd, 0x3c, 0x46, 0x96, 0x14, 0x55, 0x56, 0x5e, 0xf2, 0x47, 0xaf,
	0x0e, 0xe6, 0xdd, 0xfd, 0x96, 0x3b, 0xc6, 0x8b, 0xef, 0x30, 0x3c, 0x38, 0x9b, 0x73, 0x52, 0xc6,
	0x68, 0x34, 0xf2, 0xaa, 0xce, 0xc9, 0x97, 0xe2, 0x0d, 0x8c, 0xc8, 0xa8, 0xf8, 0xd1, 0x25, 0x52,
	0x67, 0x2f, 0xd9, 0x71, 0xde, 0xc8, 0x75, 0xfc, 0x87, 0x6f, 0xe9, 0xd9, 0xd1, 0x5b, 0xba, 0xef,
	0xf2, 0xfb, 0x7e, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xde, 0x9c, 0x5f, 0xef, 0x03, 0x00,
	0x00,
}
