// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rorders.proto

package orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ROrder struct {
	FulfilmentOrderId    int32            `protobuf:"varint,1,opt,name=fulfilment_order_id,json=fulfilmentOrderId,proto3" json:"fulfilment_order_id,omitempty"`
	CustomerOrderId      string           `protobuf:"bytes,2,opt,name=customer_order_id,json=customerOrderId,proto3" json:"customer_order_id,omitempty"`
	CreatedAt            string           `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Units                []*Unit          `protobuf:"bytes,4,rep,name=units,proto3" json:"units,omitempty"`
	ShipmentAddress      *ShipmentAddress `protobuf:"bytes,5,opt,name=shipment_address,json=shipmentAddress,proto3" json:"shipment_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ROrder) Reset()         { *m = ROrder{} }
func (m *ROrder) String() string { return proto.CompactTextString(m) }
func (*ROrder) ProtoMessage()    {}
func (*ROrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_4538a94035861e9a, []int{0}
}

func (m *ROrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ROrder.Unmarshal(m, b)
}
func (m *ROrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ROrder.Marshal(b, m, deterministic)
}
func (m *ROrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ROrder.Merge(m, src)
}
func (m *ROrder) XXX_Size() int {
	return xxx_messageInfo_ROrder.Size(m)
}
func (m *ROrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ROrder.DiscardUnknown(m)
}

var xxx_messageInfo_ROrder proto.InternalMessageInfo

func (m *ROrder) GetFulfilmentOrderId() int32 {
	if m != nil {
		return m.FulfilmentOrderId
	}
	return 0
}

func (m *ROrder) GetCustomerOrderId() string {
	if m != nil {
		return m.CustomerOrderId
	}
	return ""
}

func (m *ROrder) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ROrder) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *ROrder) GetShipmentAddress() *ShipmentAddress {
	if m != nil {
		return m.ShipmentAddress
	}
	return nil
}

type ShipmentAddress struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CompanyName          string   `protobuf:"bytes,4,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Street               string   `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber          string   `protobuf:"bytes,6,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	Zip                  string   `protobuf:"bytes,12,opt,name=zip,proto3" json:"zip,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	ShippingDetails      string   `protobuf:"bytes,10,opt,name=shipping_details,json=shippingDetails,proto3" json:"shipping_details,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentAddress) Reset()         { *m = ShipmentAddress{} }
func (m *ShipmentAddress) String() string { return proto.CompactTextString(m) }
func (*ShipmentAddress) ProtoMessage()    {}
func (*ShipmentAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_4538a94035861e9a, []int{1}
}

func (m *ShipmentAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentAddress.Unmarshal(m, b)
}
func (m *ShipmentAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentAddress.Marshal(b, m, deterministic)
}
func (m *ShipmentAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentAddress.Merge(m, src)
}
func (m *ShipmentAddress) XXX_Size() int {
	return xxx_messageInfo_ShipmentAddress.Size(m)
}
func (m *ShipmentAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentAddress proto.InternalMessageInfo

func (m *ShipmentAddress) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ShipmentAddress) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ShipmentAddress) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ShipmentAddress) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *ShipmentAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *ShipmentAddress) GetHouseNumber() string {
	if m != nil {
		return m.HouseNumber
	}
	return ""
}

func (m *ShipmentAddress) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ShipmentAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ShipmentAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ShipmentAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ShipmentAddress) GetShippingDetails() string {
	if m != nil {
		return m.ShippingDetails
	}
	return ""
}

func (m *ShipmentAddress) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Unit struct {
	IdOrderUnit             int32         `protobuf:"varint,1,opt,name=id_order_unit,json=idOrderUnit,proto3" json:"id_order_unit,omitempty"`
	FreightCosts            float32       `protobuf:"fixed32,2,opt,name=freight_costs,json=freightCosts,proto3" json:"freight_costs,omitempty"`
	IsCancelled             bool          `protobuf:"varint,3,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	Sku                     string        `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Price                   float32       `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	DeliveryTimeExpires     string        `protobuf:"bytes,6,opt,name=delivery_time_expires,json=deliveryTimeExpires,proto3" json:"delivery_time_expires,omitempty"`
	ShipmentData            *ShipmentData `protobuf:"bytes,7,opt,name=shipment_data,json=shipmentData,proto3" json:"shipment_data,omitempty"`
	CustomerOrderUnitStatus string        `protobuf:"bytes,8,opt,name=customer_order_unit_status,json=customerOrderUnitStatus,proto3" json:"customer_order_unit_status,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4538a94035861e9a, []int{2}
}

func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (m *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(m, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

func (m *Unit) GetIdOrderUnit() int32 {
	if m != nil {
		return m.IdOrderUnit
	}
	return 0
}

func (m *Unit) GetFreightCosts() float32 {
	if m != nil {
		return m.FreightCosts
	}
	return 0
}

func (m *Unit) GetIsCancelled() bool {
	if m != nil {
		return m.IsCancelled
	}
	return false
}

func (m *Unit) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Unit) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Unit) GetDeliveryTimeExpires() string {
	if m != nil {
		return m.DeliveryTimeExpires
	}
	return ""
}

func (m *Unit) GetShipmentData() *ShipmentData {
	if m != nil {
		return m.ShipmentData
	}
	return nil
}

func (m *Unit) GetCustomerOrderUnitStatus() string {
	if m != nil {
		return m.CustomerOrderUnitStatus
	}
	return ""
}

type ShipmentData struct {
	Carrier              string   `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrackingNumber       string   `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentData) Reset()         { *m = ShipmentData{} }
func (m *ShipmentData) String() string { return proto.CompactTextString(m) }
func (*ShipmentData) ProtoMessage()    {}
func (*ShipmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4538a94035861e9a, []int{3}
}

func (m *ShipmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentData.Unmarshal(m, b)
}
func (m *ShipmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentData.Marshal(b, m, deterministic)
}
func (m *ShipmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentData.Merge(m, src)
}
func (m *ShipmentData) XXX_Size() int {
	return xxx_messageInfo_ShipmentData.Size(m)
}
func (m *ShipmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentData.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentData proto.InternalMessageInfo

func (m *ShipmentData) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *ShipmentData) GetTrackingNumber() string {
	if m != nil {
		return m.TrackingNumber
	}
	return ""
}

func (m *ShipmentData) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*ROrder)(nil), "orders.rOrder")
	proto.RegisterType((*ShipmentAddress)(nil), "orders.Shipment_address")
	proto.RegisterType((*Unit)(nil), "orders.Unit")
	proto.RegisterType((*ShipmentData)(nil), "orders.Shipment_data")
}

func init() {
	proto.RegisterFile("rorders.proto", fileDescriptor_4538a94035861e9a)
}

var fileDescriptor_4538a94035861e9a = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x6f, 0x13, 0x3f,
	0x10, 0x55, 0xd2, 0x24, 0xed, 0xce, 0x26, 0xbf, 0xb6, 0xee, 0xaf, 0x60, 0x81, 0x90, 0x42, 0x38,
	0x10, 0x38, 0xf4, 0x10, 0x6e, 0x70, 0xaa, 0x5a, 0x0e, 0x5c, 0x8a, 0xb4, 0x85, 0xf3, 0xca, 0xdd,
	0x9d, 0x34, 0x56, 0xf7, 0x1f, 0xf6, 0x2c, 0x22, 0x7c, 0x41, 0x3e, 0x03, 0xdf, 0x81, 0x0f, 0x81,
	0x3c, 0xb6, 0xa9, 0x1a, 0x24, 0x6e, 0x33, 0xef, 0xbd, 0xb5, 0x3c, 0x6f, 0x9e, 0x17, 0x66, 0xa6,
	0x35, 0x25, 0x1a, 0x7b, 0xd6, 0x99, 0x96, 0x5a, 0x31, 0xf1, 0xdd, 0xe2, 0xd7, 0x00, 0x26, 0xe6,
	0xa3, 0xab, 0xc5, 0x19, 0x9c, 0xac, 0xfb, 0x6a, 0xad, 0xab, 0x1a, 0x1b, 0xca, 0x99, 0xcf, 0x75,
	0x29, 0x07, 0xf3, 0xc1, 0x72, 0x9c, 0x1d, 0xdf, 0x53, 0xac, 0xfe, 0x50, 0x8a, 0xd7, 0x70, 0x5c,
	0xf4, 0x96, 0xda, 0x1a, 0xcd, 0xbd, 0x7a, 0x38, 0x1f, 0x2c, 0x93, 0xec, 0x30, 0x12, 0x51, 0xfb,
	0x0c, 0xa0, 0x30, 0xa8, 0x08, 0xcb, 0x5c, 0x91, 0xdc, 0x63, 0x51, 0x12, 0x90, 0x73, 0x12, 0x0b,
	0x18, 0xf7, 0x8d, 0x26, 0x2b, 0x47, 0xf3, 0xbd, 0x65, 0xba, 0x9a, 0x9e, 0x85, 0xbb, 0x7e, 0x6e,
	0x34, 0x65, 0x9e, 0x12, 0x17, 0x70, 0x64, 0x37, 0xba, 0xe3, 0xcb, 0xa9, 0xb2, 0x34, 0x68, 0xad,
	0x1c, 0xcf, 0x07, 0xcb, 0x74, 0x25, 0xa3, 0xfc, 0x7a, 0x87, 0xcf, 0x0e, 0xe3, 0x17, 0xe7, 0x1e,
	0x58, 0xfc, 0x1c, 0xc2, 0xd1, 0xae, 0x4a, 0xfc, 0x0f, 0x63, 0xd2, 0x54, 0x21, 0x8f, 0x9a, 0x64,
	0xbe, 0x71, 0x57, 0x5e, 0x6b, 0x63, 0x29, 0x6f, 0x54, 0x8d, 0x61, 0xae, 0x84, 0x91, 0x2b, 0x55,
	0xa3, 0x78, 0x0a, 0x49, 0xa5, 0x22, 0xeb, 0x07, 0x3a, 0x70, 0x00, 0x93, 0xcf, 0x61, 0x5a, 0xb4,
	0x75, 0xa7, 0x9a, 0xad, 0xe7, 0x47, 0xcc, 0xa7, 0x01, 0x63, 0xc9, 0x23, 0x98, 0x58, 0x32, 0x88,
	0xc4, 0x43, 0x24, 0x59, 0xe8, 0xdc, 0xa7, 0x9b, 0xb6, 0xb7, 0x98, 0x37, 0x7d, 0x7d, 0x83, 0x46,
	0x4e, 0xfc, 0xa7, 0x8c, 0x5d, 0x31, 0x24, 0x8e, 0x60, 0xef, 0xbb, 0xee, 0xe4, 0x94, 0x19, 0x57,
	0x0a, 0x01, 0xa3, 0x42, 0xd3, 0x56, 0xee, 0x33, 0xc4, 0xb5, 0x90, 0xb0, 0x5f, 0xb4, 0x7d, 0x43,
	0x66, 0x2b, 0x0f, 0x18, 0x8e, 0xad, 0x9b, 0xb7, 0xdb, 0xb4, 0x0d, 0xca, 0xc4, 0xcf, 0xcb, 0x8d,
	0x78, 0xe5, 0xfd, 0xed, 0x74, 0x73, 0x9b, 0x97, 0x48, 0x4a, 0x57, 0x56, 0x82, 0xdf, 0x66, 0xc4,
	0x2f, 0x3d, 0xec, 0x0e, 0xc0, 0x5a, 0xe9, 0x4a, 0xa6, 0xfe, 0x00, 0x6e, 0x16, 0x3f, 0x86, 0x30,
	0x72, 0x0b, 0x13, 0x0b, 0x98, 0xe9, 0x32, 0x44, 0xc2, 0xed, 0x2e, 0x44, 0x28, 0xd5, 0x25, 0xc7,
	0x81, 0x35, 0x2f, 0x60, 0xb6, 0x36, 0xa8, 0x6f, 0x37, 0x94, 0x17, 0xad, 0x25, 0xcb, 0x06, 0x0f,
	0xb3, 0x69, 0x00, 0x2f, 0x1c, 0xe6, 0xbc, 0xd0, 0x36, 0x2f, 0x54, 0x53, 0x60, 0x55, 0x61, 0xc9,
	0x36, 0x1f, 0x64, 0xa9, 0xb6, 0x17, 0x11, 0x72, 0x5e, 0xd8, 0xbb, 0x3e, 0x18, 0xec, 0x4a, 0x9e,
	0xce, 0xe8, 0x02, 0xd9, 0xd7, 0x61, 0xe6, 0x1b, 0xb1, 0x82, 0xd3, 0x12, 0x2b, 0xfd, 0x15, 0xcd,
	0x36, 0x27, 0x5d, 0x63, 0x8e, 0xdf, 0x3a, 0x6d, 0xd0, 0x06, 0x7f, 0x4f, 0x22, 0xf9, 0x49, 0xd7,
	0xf8, 0xde, 0x53, 0xe2, 0x2d, 0xcc, 0xfe, 0x24, 0xae, 0x54, 0xa4, 0xd8, 0xde, 0x74, 0x75, 0xfa,
	0x57, 0xdc, 0x1c, 0x99, 0x4d, 0xa3, 0xf6, 0x52, 0x91, 0x12, 0xef, 0xe0, 0xc9, 0xce, 0xe3, 0x70,
	0x4e, 0xe4, 0x96, 0x14, 0xf5, 0x36, 0x2c, 0xe4, 0xf1, 0x83, 0x57, 0xe2, 0x6c, 0xb9, 0x66, 0x7a,
	0xf1, 0x05, 0x66, 0x0f, 0xce, 0xe6, 0x5d, 0x2a, 0x63, 0x34, 0x9a, 0x90, 0xd1, 0xd8, 0x8a, 0x97,
	0x70, 0x48, 0x46, 0x15, 0x77, 0x6e, 0x6b, 0x21, 0x31, 0x3e, 0xaa, 0xff, 0x45, 0x38, 0x84, 0xe6,
	0xdf, 0x2f, 0xf0, 0x66, 0xc2, 0xbf, 0x85, 0x37, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x46, 0xbd,
	0x97, 0xef, 0x27, 0x04, 0x00, 0x00,
}
